### ISSUE TITLE
How would I go about passing a value for $PSBPreference.Publish.PSRepositoryApiKey here?

### ISSUE THREAD

**Issue by mikejwhat** [devblackops/Stucco#17]
https://github.com/devblackops/Stucco/blob/dffe2290768ed2e7dbedb35daeb796682c907f5d/Stucco/template/build.ps1#L15

**Comment by jpatigny** [comment]
Hey @mikejwhat , did you find a way to do it ?

**Comment by mikejwhat** [comment]
I used a workaround - I set some environment variables in my build definition and altered psakeFile.ps1 as below:

`properties {
    $PSBPreference.Build.CompileModule = $false
    $PSBPreference.Help.DefaultLocale = 'en-GB'
    $PSBPreference.Test.OutputFile = 'out/testResults.xml'
    $PSBPreference.Publish.PSRepository = $env:PSRepository
    $PSBPreference.Publish.PSRepositoryApiKey = $env:SYSTEM_ACCESSTOKEN
}

task default -depends Test

task Test -FromModule PowerShellBuild -Version '0.4.0'
`

**Comment by jpatigny** [comment]
Did the same in the meantime.
Thanks for the feedback anyway 👍

**Comment by devblackops** [comment]
That's a good workaround @jpatigny

As an alternative, I just [added](https://github.com/devblackops/Stucco/commit/9d1d72bc6c2e837d0bc9e483df2d410bda8816c9) a new parameter to the module template build script called `Parameters` . These are [psake parameters](https://psake.readthedocs.io/en/latest/pass-parameters/) which are processed BEFORE the `psake` properties` block. This means you can assign variables in the properties block with them.

Example

```powershell
./build.ps1 -task test -parameters @{ApiKey= '123'}
```

#### psakeFile.ps1
```powershell
properties {
    # ApiKey is passed via psake parameters
    $PSBPreference.Publish.PSRepositoryApiKey = $ApiKey
}
```
