### ISSUE TITLE
Module description not set correctly. 

### ISSUE THREAD

**Issue by ngetchell** [devblackops/Stucco#2]
When invoking plaster using the stucco template you are prompted to set a description but it never makes it to the PSD1 file. 

## Expected Behavior
When prompted for a description, it should carry over to the PSD1 file. 

## Current Behavior
The psd1 file has a commented out Description with no text. 

## Possible Solution
There are two different names for the attribute used in the manifest. They are as follows.

``` xml
    <parameter name='Description'
               type='text'
               prompt='Enter a description of the module'/>
```

``` xml
    <newModuleManifest destination='${PLASTER_PARAM_ModuleName}\${PLASTER_PARAM_ModuleName}.psd1'
                       moduleVersion='$PLASTER_PARAM_Version'
                       rootModule='${PLASTER_PARAM_ModuleName}.psm1'
                       author='$PLASTER_PARAM_FullName'
                       description='$PLASTER_PARAM_ModuleDesc'
                       encoding='UTF8-NoBOM'/>
```

I tried setting the variables to the same name but no luck. 

## Steps to Reproduce (for bugs)
$Template = Get-PlasterTemplate -Path .\Output\Stucco\0.1.0\plasterManifest.xml
Invoke-Plaster -TemplatePath $template.TemplatePath -DestinationPath "c:\users\ngetchell\documents\git\Example3"

## Context
Luckily the pester tests catch the error. 

## Your Environment

* Module version used: 0.1.0                          
* Operating System: Microsoft Windows 10.0.17763
* PowerShell version: 6.1.0

**Comment by ngetchell** [comment]
Note: when setting a default value in the manifest that _also_ fails to make it to the psd1 file. I think there may be an issue with Plaster itself.

**Comment by devblackops** [comment]
I noticed this last night but didn't push my changes. Try now.

**Comment by ngetchell** [comment]
We came to the same conclusion. The push fixes this for me.

**Comment by ngetchell** [comment]
Resolved by the latest commit.
