### ISSUE TITLE
Ignore Initialize.ps1 when we don't have one

### ISSUE THREAD

**Issue by webtroter** [devblackops/Stucco#24]
**Description**
I don't use (or even have) the Initialize.ps1, and it makes the psm1 fail.

**Steps to Reproduce**
New module from templace, no classes, no mkdocs, with gitlab CI.

**Current Behavior**
When trying to load the module it fails because it cannot dot source the initialize.ps1

**Expected behavior**
No error on module import

**Possible Solution**
Test-path initialize.ps1 in the psm1 before dot-sourcing it.

**Environment**

* Module version used: 3.1, freshly updated
* Operating System and PowerShell version: Win10 20H2 and PS 7.1

PS : I tried finding that code on GitHub but I think it hasn't been pushed here. Is that possible? The only reference to that line is on the powershell gallery :(

Thanks a lot for your work!

**Comment by tmidthjell** [comment]
Still same problem, any update?

**Comment by devblackops** [comment]
@webtroter @tmidthjell 

Eeek! Looks like some code got leeked into that version that wasn't ready. I've just released [0.4.0](https://www.powershellgallery.com/packages/Stucco/0.4.0) that should fix this. Sorry about that!
