### ISSUE TITLE
Pester tests failing due to missing help function

### ISSUE THREAD

**Issue by DelectableMechanisations** [devblackops/Stucco#26]
**Description**
After creating a new module and executing the build.ps1 script the pester tests are failing with the following error messages:
```
Running tests from 'C:\!_Projects\myproject\tests\Help.tests.ps1'
Describing Test help for <_.Name>
[-] Describe Test help for <_.Name> failed
  CommandNotFoundException: The term 'script:FilterOutCommonParams' is not recognized as a name of a cmdlet, function, script file, or executable program.
  Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
  at <ScriptBlock>, C:\!_Projects\myproject\tests\Help.tests.ps1:54

Describing Test help for <_.Name>
[-] Describe Test help for <_.Name> failed
  CommandNotFoundException: The term 'script:FilterOutCommonParams' is not recognized as a name of a cmdlet, function, script file, or executable program.
  Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
  at <ScriptBlock>, C:\!_Projects\myproject\tests\Help.tests.ps1:54

Describing Test help for <_.Name>
[-] Describe Test help for <_.Name> failed
  CommandNotFoundException: The term 'script:FilterOutCommonParams' is not recognized as a name of a cmdlet, function, script file, or executable program.
  Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
  at <ScriptBlock>, C:\!_Projects\myproject\tests\Help.tests.ps1:54
```

**Current Behavior**
Individual function based Pester tests fail to run.

**Expected behavior**
Individual function based Pester tests successfully run.

**Possible Solution**
In ".\tests\Help.tests.ps1" I removed the "script" scope from all references to the "FilterOutCommonParams" function and moved this into its own external module file ".\tests\HelpFunctions.psm1".
Then I removed the "FilterOutCommonParams" function from the "BeforeDiscovery" code block and replaced this with an Import-Module:
```powershell
BeforeDiscovery {
    # Make sure HelpFunctions.psm1 is loaded - it contains FilterOutCommonParams
    Import-Module -Name (Join-Path -Path $PSScriptRoot -ChildPath 'HelpFunctions.psm1') -Verbose:$false -Force

    $manifest             = Import-PowerShellDataFile -Path $env:BHPSModuleManifest
    $outputDir            = Join-Path -Path $env:BHProjectPath -ChildPath 'Output'
    $outputModDir         = Join-Path -Path $outputDir -ChildPath $env:BHProjectName
    $outputModVerDir      = Join-Path -Path $outputModDir -ChildPath $manifest.ModuleVersion
    $outputModVerManifest = Join-Path -Path $outputModVerDir -ChildPath "$($env:BHProjectName).psd1"
     ...
```

I tried experimenting with BeforeAll blocks and a few other things but this was the only solution I tried that work in both PowerShell 7 and VSCode.

To allow the Tasks to run from VSCode (Ctrl + P; task; Test) the .vscode\tasks.json file also needs the PowerShell executable path updating to "C:\\Program Files\\PowerShell\\7\\pwsh.exe" because PowerShell 5.1 fails at INIT with:
```
Exception: Method invocation failed because [System.IO.Path] does not contain a method named 'IsPathFullyQualified'
```

**Environment**
* Module version used:
```
ModuleType Version    PreRelease Name
---------- -------    ---------- ----
Script     2.0.16                BuildHelpers
Script     0.6.1                 PowerShellBuild
Script     4.9.0                 psake
Script     1.19.1                PSScriptAnalyzer
```

* Operating System and PowerShell version:
```
Name                           Value
----                           -----
PSVersion                      7.1.3
PSEdition                      Core
GitCommitId                    7.1.3
OS                             Microsoft Windows 10.0.18363
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by HeyItsGilbert** [comment]
Can you check what version of Pester you have loaded?

**Comment by FLeven** [comment]
I get the same error, after starting a build of my new modul:

`Running tests from 'C:\Users\*\Documents\git\CCM\tests\Help.tests.ps1'
Describing Test help for <_.Name>
[-] Describe Test help for <_.Name> failed
  CommandNotFoundException: The term 'script:FilterOutCommonParams' is not recognized as a name of a cmdlet, function, script file, or executable program.
  Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
  at <ScriptBlock>, C:\Users\*\Documents\git\CCM\tests\Help.tests.ps1:54`

Build System Details:
Build Module:       PowerShellBuild:0.6.1
PowerShell Version: 7.2.1
Pester v5.3.1

**Comment by stuartluscombe** [comment]
> @devblackops Should `script:FilterOutCommonParams` be global? I think that's what I had to do with mine to work: https://github.com/HeyItsGilbert/RPGDice/runs/3519100933?check_suite_focus=true
> 
> My bad. I must have missed that I changed that in mine. I should have caught it and submitted a PR.

This change fixed it for me. The merged code must not be in the current release though as I only installed Stucco and started my current module a couple of days ago and got this error.

**Comment by devblackops** [comment]
[v0.5.0](https://www.powershellgallery.com/packages/Stucco/0.5.0) has been released with this fix.
