### ISSUE TITLE
Help.Tests.ps1 errors

### ISSUE THREAD

**Issue by quonic** [devblackops/Stucco#32]
**Description**
When running build.ps1 you get errors.

**Steps to Reproduce**

1. Create a module
2. Run .\build.ps1

**Current Behavior**
```
Describing Test help for <_.Name>
[-] Describe Test help for <_.Name> failed
  CommandNotFoundException: The term 'script:FilterOutCommonParams' is not recognized as a name of a cmdlet, function, script file, or executable program.
  Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
  at <ScriptBlock>, E:\Code\libguestfsPS\tests\Help.tests.ps1:54
```

**Expected behavior**
Shouldn't produce test errors after creating module from template.

**Possible Solution**
In Help.tests.ps1 , lines 44, 54, and 56:
Replace `script:FilterOutCommonParams` with `FilterOutCommonParams`

**Screenshots**
N/A

**Environment**

* Module version used: 0.4.0
* Operating System and PowerShell version:
```
Name                           Value
----                           -----
PSVersion                      7.2.2
PSEdition                      Core
GitCommitId                    7.2.2
OS                             Microsoft Windows 10.0.19043
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Additional context**
N/A

**Comment by devblackops** [comment]
@quonic This is resolved in #27. Are you pulling the latest from `main`?

**Comment by quonic** [comment]
@devblackops Installed from powershell gallery, v0.4.0.

**Comment by HeyItsGilbert** [comment]
@devblackops Looks like 0.4.0 does have the old one. I'm guessing a new version of the module just needs to be published? I didn't see a GH action to publish. https://www.powershellgallery.com/packages/Stucco/0.4.0/Content/template%5Ctests%5CHelp.tests.ps1

**Comment by devblackops** [comment]
@HeyItsGilbert @quonic 

[v0.5.0](https://www.powershellgallery.com/packages/Stucco/0.5.0) has been released with this fix. Sorry I slept on this for so long.
